# Generated by Django 4.0 on 2023-08-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_buyer_farmer_remove_jobapplication_job_posting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_image',
            field=models.ImageField(default='image', upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
