# Generated by Django 4.0 on 2023-08-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_buyer_profile_image_farmer_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='profile_image',
        ),
    ]
