# Generated by Django 4.0 on 2023-08-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
