# Generated by Django 4.0 on 2023-08-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmer'),
        ),
    ]
